### ISSUE TITLE
Npm start doesn't work the first time

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/WebBlocks#19]
Due to the current setup, npm start doesn't work at the very first try after cloning the repo.

## Workaround
After cloning run `npm install` 
Then run `npm run build`
Afterwards, `npm start` will work again

**Comment by rwiteshbera** [comment]
It is not an issue, you have to use `npm install` to get the node_modules. Afterwards you can run `npm start`

**Comment by IM-Deane** [comment]
Unfortunately, some people may encounter an issue when trying to run the project after installing the node_modules. The attached screenshots depict the error.

The steps to reproduce the bug (from a **fresh** install):
1. git clone https://github.com/zero-to-mastery/WebBlocks.git
2. cd WebBlocks
3. npm install
4. npm start

We are looking into the issue, but the workaround highlighted above should solve the problem.

![web-block-build-error](https://user-images.githubusercontent.com/59102133/135680060-3278739d-dc2d-4f39-a8e6-be6c47b74c1e.png)
<img width="739" alt="web-block-build-error-terminal" src="https://user-images.githubusercontent.com/59102133/135680070-a3f65763-6823-4c4e-b5f3-d4188aa86ac6.png">

**Comment by Chetan-khachane** [comment]
> Due to the current setup, npm start doesn't work on the very first try after cloning the repo.
> 
> ## Workaround
> After cloning run `npm install` Then run `npm run build` Afterwards, `npm start` will work again

Hi , It worked!
Thank you so much. 

one thing I want to ask you is that whenever we stop the dev server then if we made changes then again we have to do npm build and then npm start.

**Comment by Chetan-khachane** [comment]
The solution provided by @r4pt0s works for me.

**Comment by Chetan-khachane** [comment]
![image](https://user-images.githubusercontent.com/70019702/135705264-c395beb6-5572-4fe8-a1c6-8c2c41ba263b.png)
I am again encountering the same problem, even after I followed the workaround provided by @r4pt0s. It only works when cloning our repo for the first time and everything is fresh and later if we change something then it again shows the above-described error.

**Comment by Chetan-khachane** [comment]
i think the problem is related to webblocks.css

**Comment by Chetan-khachane** [comment]
![image](https://user-images.githubusercontent.com/70019702/135705434-06aef46b-e349-4a42-b951-5d230de3391a.png)
this something come after doing ```npm run build```

**Comment by Chetan-khachane** [comment]
i think the error is coming due 'stencil.config.ts', it throws an error: Cannot find name 'process'.

**Comment by r4pt0s** [comment]
Thanks for sharing your thoughts. We are still investigating why this is happening now.

I just can give you a typical answer for now, it worked for me after setting this project up 😅.

I will look into it today and hopefully merge a fix today.

**Comment by Chetan-khachane** [comment]
> Thanks for sharing your thoughts. We are still investigating why this is happening now.
> 
> I just can give you a typical answer for now, it worked for me after setting this project up 😅.
> 
> I will look into it today and hopefully merge a fix today.

i installed ```@types/node``` and tried to import but it says :

![image](https://user-images.githubusercontent.com/70019702/135706155-dfa3ca8d-0e30-4961-8498-7141eca5cffe.png)


this is changes that I made in stencil.config.ts:

![image](https://user-images.githubusercontent.com/70019702/135706182-26f871d8-803b-4b74-aac6-dc6b567e47f7.png)

**Comment by Chetan-khachane** [comment]
when I tried in node, ```process.env.PWD``` it returns ```undefined```. it must be a path issue i think.

**Comment by Chetan-khachane** [comment]
From me and @IM-Deane , i think it is a path issue in stencil.config.ts.

**Comment by r4pt0s** [comment]
Should be fixed now @Chetan-khachane 
Please pull the latest changes from main
