### ISSUE TITLE
Modal Component 

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/WebBlocks#2]
The goal of this component is to create a modal window component.
It should receive a titel, okay-text and cancel-text prop and also content via slots.

Further information if needed gets added in this issue.

**Comment by Chetan-khachane** [comment]
Hi, I started working on this component.

**Comment by r4pt0s** [comment]
@Chetan-khachane
Go for it 💪🏻

**Comment by Chetan-khachane** [comment]
when I write npm start, it throws an error. 
why is this is happening?
![image](https://user-images.githubusercontent.com/70019702/135662461-abd1bda5-644f-4b91-a217-fdccf78caf5a.png)

**Comment by IM-Deane** [comment]
Hi @Chetan-khachane, it looks like you may not have built the project yet.
From the root of the project please try running:
```
npm run build
npm start
```

**Comment by Chetan-khachane** [comment]
@r4pt0s  what do you mean by "content via slots" ?

**Comment by r4pt0s** [comment]
@Chetan-khachane
Web components can receive content via slot name.
This slot name can be used to place the content within your web component where you want it to be.
Have a look at [the stenciljs docs](https://stenciljs.com/docs/templating-jsx#slots) to see how it is done with stencil.

**Comment by Chetan-khachane** [comment]
Hi, @r4pt0s, sorry to disturb you. I accidentally clicked on remove assignee by myself. Can you please make me assignee again?

**Comment by Chetan-khachane** [comment]
hi, @r4pt0s, I want to ask you that, whether we should make a button that displays a modal window or leave it for a user to set the button.

**Comment by Chetan-khachane** [comment]
@r4pt0s, I want to make pr. Do I have to do ```npm run build``` before making pr or just push my chages?

**Comment by r4pt0s** [comment]
@Chetan-khachane
Just make your changes and make a PR to the dev branch.
The project gets build automatically by github actions.

**Comment by Chetan-khachane** [comment]
![image](https://user-images.githubusercontent.com/70019702/135745425-abdd5487-78df-46ea-897a-af95310fb520.png)
is this is correct ?
i pushed via ```git push origin modal -window```. I created a new branch called modal-window.please reply

**Comment by Chetan-khachane** [comment]
> ![image](https://user-images.githubusercontent.com/70019702/135745425-abdd5487-78df-46ea-897a-af95310fb520.png) is this is correct ? i pushed via `git push origin modal -window`. I created a new branch called modal-window.please reply

@r4pt0s

**Comment by Chetan-khachane** [comment]
![image](https://user-images.githubusercontent.com/70019702/135745530-a86624ec-5fda-458e-a4e1-c7c9360480ab.png)
this is coming main ztm repo

**Comment by Chetan-khachane** [comment]
why it is saying ' Can't automatically  merge'?

**Comment by Chetan-khachane** [comment]
@r4pt0s , I am facing merge conflict in component.d.ts. help me
