### ISSUE TITLE
Google tag manager component

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/WebBlocks#3]
More of a behind the scenes component but usually if you want to implement a Google tag manager script you need to have Javascript enabled anyway so it is a good use-case.

This component needs to receive at least the contained ID as prop.
More information about what this is can be found [here](https://developers.google.com/tag-platform/tag-manager/web)

**Comment by SneakySensei** [comment]
Hello maintainers! I've started working on this, can you assign me this issue?

Regards,
Snehil

**Comment by r4pt0s** [comment]
We will review your PR and let you know the result of it

**Comment by Chetan-khachane** [comment]
> Hello maintainers! I've started working on this, can you assign me this issue?
> 
> Regards, Snehil

hi,
did you face this error while making :
![image](https://user-images.githubusercontent.com/70019702/135664798-d642e6ae-dc76-4fc4-83e4-b94b22847d59.png)
