### ISSUE TITLE
Misleading instructions in CONTRIBUTING.md Git Workflow

### ISSUE THREAD

**Issue by OPerel** [zero-to-mastery/WebBlocks#40]
Hello,
I just followed the instructions under the `Git Workflow` section of `CONTRIBUTING.md` and found two problems with it.
1. right after the instructions for cloning and adding the `upstream` remote it says to keep local repo up to date. I.e. to run `git pull` both from `upstream dev` and `upstream main`. The problem is people might run `git pull upstream dev` before checking out the `dev` branch which will result in pulling in latest changes from `upstream dev` into their local `main`. 
2. Secondly, after that, when it does say to check out `dev` it says to run the command `git checkout dev`. But as the `upstream` remote has already been added it gives an error:
    ```
    error: pathspec 'dev' did not match any file(s) known to git
    hint: 'dev' matched more than one remote tracking branch.
    hint: We found 2 remotes with a reference that matched. So we fell back
    hint: on trying to resolve the argument as a path, but failed there too!
    hint: 
    hint: If you meant to check out a remote tracking branch on, e.g. 'origin',
    hint: you can do so by fully qualifying the name with the --track option:
    hint: 
    hint:     git checkout --track origin/<name>
    hint: 
    hint: If you'd like to always have checkouts of an ambiguous <name> prefer
    hint: one remote, e.g. the 'origin' remote, consider setting
    hint: checkout.defaultRemote=origin in your config.
    ```
    As the error suggests, the command should be `git checkout --track origin/dev` .

I can open PR with a fix if you like

**Comment by Chetan-khachane** [comment]
Yes, you are correct.

**Comment by r4pt0s** [comment]
You are absolutely right @OPerel.
Would be awesome if you could fix it.
Go for it 💪🏻

**Comment by OPerel** [comment]
Opened PR #47
