### ISSUE TITLE
Nav link with a bottom underline going left to right on hover

### ISSUE THREAD

**Issue by the-halfbloodprince** [zero-to-mastery/WebBlocks#41]
Nav link with a bottom underline going left to right on hover, like the one below:

https://user-images.githubusercontent.com/55590289/136278166-84858d9d-2545-4a22-9f48-3758dceb1c78.mp4

**Comment by the-halfbloodprince** [comment]
I want to work on it. Can this be assigned to me please?

**Comment by r4pt0s** [comment]
Awesome idea. 
Do you have planned to also add nav items support to it? 
Go for it 💪🏻

**Comment by the-halfbloodprince** [comment]
Yeah I was actually planning to create just a nav item with this animation as that would provide more flexibility, or the other idea is to take an array and each array item corresponds to a nav link, but people mostly just need the first option, what are your opinions on this, @r4pt0s ? Which option looks more helpful?

**Comment by r4pt0s** [comment]
Totally.
Let's start with the first approach which you have mentioned @the-halfbloodprince.
That is also easier and clearer to use.
