### ISSUE TITLE
Component's API documentation

### ISSUE THREAD

**Issue by OPerel** [zero-to-mastery/WebBlocks#43]
What about documentation on how to use the different components?
As a start stencil can be used to auto generate docs in [markdown](https://stenciljs.com/docs/docs-readme), [JSON](https://stenciljs.com/docs/docs-json), and a [custom format](https://stenciljs.com/docs/docs-custom).
Or each contributor can add a short API doc and usage guide in a general MD file.

I'd be happy to get this started if you like

**Comment by r4pt0s** [comment]
That would be awesome @OPerel. 
Go for it 💪🏻
