### ISSUE TITLE
Alert Component

### ISSUE THREAD

**Issue by jomefavourite** [zero-to-mastery/WebBlocks#44]
I'll love to work on an alert component, which showcases error messages, success messages and so on

**Comment by r4pt0s** [comment]
Awesome idea @jomefavourite.
I'm curious with what you will come up with. 
Go for it 💪🏻

**Comment by jomefavourite** [comment]
> Awesome idea @jomefavourite.
> I'm curious with what you will come up with. 
> Go for it 💪🏻

Thanks 😊
