### ISSUE TITLE
Hamburger menu

### ISSUE THREAD

**Issue by Chetan-khachane** [zero-to-mastery/WebBlocks#63]
Hi, I am interested to make it. Can you assign me?

**Comment by r4pt0s** [comment]
Awesome.
This is what is missing.
Good idea.
Go for it @Chetan-khachane 💪🏻

**Comment by debersole81** [comment]
Could I help with this component?

**Comment by r4pt0s** [comment]
@Chetan-khachane, any chance @debersole81 can help out developing this component together with you?

**Comment by Chetan-khachane** [comment]
@r4pt0s @r4pt0s @r4pt0s, @debersole81, Sorry for the late reply. I think we can help each other. I am not good at design. Can you help me in designing, rest of the functionalities I can give with ts. I will be glad if we can work together.
I did 30% of the work.

**Comment by r4pt0s** [comment]
@debersole81 can you help out with design tasks?

**Comment by debersole81** [comment]
Yes, I'm happy to. @Chetan-khachane, is there a branch that you're working in?

**Comment by Chetan-khachane** [comment]
I am working on a forked version. Currently working on the dev branch. 
@debersole81
