### ISSUE TITLE
Will this project continue past HacktoberFest 2021?

### ISSUE THREAD

**Issue by jselmani** [zero-to-mastery/WebBlocks#64]
Hi WebBlocks team,

I'm interested in contributing but may not be able to in October.  Is this project going to continue past HacktoberFest 2021?  If so, I will make a PR at some point soon.

If not, 😞 

Let me know and feel free to close the issue afterwards 💯

**Comment by r4pt0s** [comment]
Hi @jselmani,

This project will be alive after October as well.
We just used the Hacktoberfest to kick start it. 

Feel free to contribute at any time.

**Comment by jselmani** [comment]
Awesome thanks @r4pt0s!  I'll be sure to come back and do so.
