### ISSUE TITLE
Typewriter effect component

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/WebBlocks#72]
Everybody loves the typewriter effect I guess.
Goal of this component is to implement it everywhere easily.

It should receive the content via a slot.
Props should get added as you see fit.
The most important thing is that the speed of this effect I depending on the number of characters which the string contains in the slot.

As a reference, head of to [this blog post](https://www.sitepoint.com/css-typewriter-effect/)

**Comment by devaang21** [comment]
please assign me this issue

**Comment by r4pt0s** [comment]
@devaang21
Go for it 💪🏻
