### ISSUE TITLE
Notification badge component.

### ISSUE THREAD

**Issue by Chetan-khachane** [zero-to-mastery/WebBlocks#79]
![Screenshot_20211020-084456_Chrome](https://user-images.githubusercontent.com/70019702/138022385-d85edf75-7a85-437d-b453-9c1382a24fb6.jpg)
I want to design this component.
@r4pt0s, Can you assign me.

**Comment by r4pt0s** [comment]
Sure @Chetan-khachane.
Go for it 💪🏻
