### ISSUE TITLE
Added text-style component

### ISSUE THREAD

**Issue by haiderlikesrust** [zero-to-mastery/WebBlocks#88]
This component can do so much with text by using 3rd party libraries such as Bootsrap
- It has some attributes, like if you want italic text or bold
- How much font-weight
- You can use custom classes
- You can use Bootstrap classes 
So much You can do!!!

**Comment by r4pt0s** [comment]
Please remove bootstrap as dependency because it is quite heavy in size.
One of the advantages which web components offer is, that they are light weight.

If someone wants to use bootstrap, why should they also add a webcm component instead of using bootstrap directly?
