### ISSUE TITLE
Image component

### ISSUE THREAD

**Issue by r4pt0s** [zero-to-mastery/WebBlocks#9]
This one might look easier as it might be to implement.
The goal of this component is to make use of the html picture element.

It should receive at least three props,.
1. src-dir-jpg
2. src-dir-webp
3. src-img-name

Internally it should then create the picture element which makes use of srcset and define at least both img elements.

As a reference, head over to [this website ](https://www.industrialempathy.com/posts/image-optimizations/)

**Comment by Insidiae** [comment]
Hello, I'd like to work on this component please!

**Comment by r4pt0s** [comment]
@Insidiae
Go for it 💪🏻
